name: run tests

on:
  workflow_dispatch:
    inputs:
      testName:
        description: 'Part of the test name to run'
        required: false
        default: ''

jobs:
  e2e:
    env:
      HOME: /root
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.0
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: npm ci

    - name: Running e2e tests with optional filter
      run: |
        if [ "${{ github.event.inputs.testName }}" != "" ]; then
          echo "Running tests filtered by name: ${{ github.event.inputs.testName }}"
          npx playwright test --grep "${{ github.event.inputs.testName }}"
        else
          echo "Running all tests"
          npx playwright test
        fi
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-report
        path: playwright-report/
        retention-days: 7
